import { useEffect, useMemo, useState } from "react";

type Category = "emergency" | "community" | "climate" | "education" | "healthcare" | "relief";
type Cause = { title: string; location: string; category: Category; tag: string; image: string; raised: string; goal: string; percent: number; supporters: string };

const previewCauses: Cause[] = [
  { title: "Rebuild after the coastal floods", location: "Porto Alegre, Brazil", category: "emergency", tag: "Urgent relief", image: "https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80", raised: "$84,290", goal: "$120,000", percent: 70, supporters: "1,248 supporters" },
  { title: "Warm meals for displaced families", location: "Marrakesh, Morocco", category: "community", tag: "Community care", image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80", raised: "$31,840", goal: "$45,000", percent: 71, supporters: "682 supporters" },
  { title: "Protect the last forest corridor", location: "Borneo, Indonesia", category: "climate", tag: "Climate action", image: "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=800&q=80", raised: "$19,430", goal: "$30,000", percent: 64, supporters: "409 supporters" },
  { title: "A safe roof for the neighborhood", location: "New Orleans, USA", category: "emergency", tag: "Housing", image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80", raised: "$52,180", goal: "$75,000", percent: 69, supporters: "791 supporters" },
  { title: "Keep the clinic doors open", location: "Kampala, Uganda", category: "community", tag: "Healthcare", image: "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=800&q=80", raised: "$12,650", goal: "$20,000", percent: 63, supporters: "238 supporters" },
  { title: "Restore the river, restore a future", location: "Queensland, Australia", category: "climate", tag: "Climate action", image: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=800&q=80", raised: "$27,920", goal: "$40,000", percent: 70, supporters: "518 supporters" },
  { title: "A classroom for every child", location: "Kigali, Rwanda", category: "education", tag: "Education", image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80", raised: "$18,420", goal: "$25,000", percent: 74, supporters: "356 supporters" },
  { title: "Mobile care for rural families", location: "Pune, India", category: "healthcare", tag: "Healthcare", image: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=800&q=80", raised: "$23,710", goal: "$35,000", percent: 68, supporters: "472 supporters" },
  { title: "Emergency kits for displaced families", location: "Beirut, Lebanon", category: "relief", tag: "Direct relief", image: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=800&q=80", raised: "$41,280", goal: "$60,000", percent: 69, supporters: "914 supporters" },
];

function Button({ children, onClick, className = "" }: { children: React.ReactNode; onClick?: () => void; className?: string }) { return <button type="button" className={className} onClick={onClick}>{children}</button>; }

export default function App() {
  const [causes, setCauses] = useState(previewCauses);
  const [filter, setFilter] = useState<"all" | Category>("all");
  const [query, setQuery] = useState("");
  const [visibleCount, setVisibleCount] = useState(3);
  const [toast, setToast] = useState("");
  const [alertLocation, setAlertLocation] = useState(() => localStorage.getItem("kindred-alert-location") || "");
  const [alertCategory, setAlertCategory] = useState<Category | "all">(() => (localStorage.getItem("kindred-alert-category") as Category | "all") || "all");
  const [alertsEnabled, setAlertsEnabled] = useState(() => localStorage.getItem("kindred-alerts-enabled") === "true");
  const showToast = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3500); };
  const saveAlertPreference = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!alertLocation.trim()) {
      showToast("Add a city, state, or country to get local alerts.");
      return;
    }
    localStorage.setItem("kindred-alert-location", alertLocation.trim());
    localStorage.setItem("kindred-alert-category", alertCategory);
    localStorage.setItem("kindred-alerts-enabled", "true");
    setAlertsEnabled(true);
    showToast(`Local need alerts are on for ${alertLocation.trim()}.`);
  };
  const disableAlerts = () => {
    localStorage.setItem("kindred-alerts-enabled", "false");
    setAlertsEnabled(false);
    showToast("Local need alerts are paused.");
  };

  useEffect(() => { fetch("/api/causes").then((response) => response.ok ? response.json() : Promise.reject()).then((payload) => { if (Array.isArray(payload.causes) && payload.causes.length) setCauses(payload.causes); }).catch(() => console.info("Using preview causes until the API is available.")); }, []);
  const filtered = useMemo(() => causes.filter((cause) => (filter === "all" || cause.category === filter) && (!query.trim() || `${cause.title} ${cause.location} ${cause.tag}`.toLowerCase().includes(query.toLowerCase().trim()))), [causes, filter, query]);
  const visible = filtered.slice(0, visibleCount);
  const selectFilter = (value: "all" | Category) => { setFilter(value); setVisibleCount(3); };
  const categories: { value: Category; label: string; icon: string; description: string }[] = [
    { value: "relief", label: "Direct relief", icon: "✦", description: "Food, shelter, and essentials" },
    { value: "emergency", label: "Natural disasters", icon: "⌁", description: "Respond to urgent events" },
    { value: "education", label: "Education", icon: "⌂", description: "Give every learner a chance" },
    { value: "healthcare", label: "Healthcare", icon: "＋", description: "Care for people everywhere" },
    { value: "climate", label: "Climate", icon: "♧", description: "Protect our shared home" },
    { value: "community", label: "Community", icon: "◎", description: "Strengthen neighborhoods" },
  ];

  return <>
    <header className="site-header"><a className="brand" href="#discover" aria-label="Kindred home"><span className="brand-mark" aria-hidden="true">✦</span><span>kindred</span></a><nav className="main-nav" aria-label="Main navigation"><a className="active" href="#discover">Discover</a><a href="#how-it-works">How it works</a><a href="#impact">Our impact</a></nav><div className="header-actions"><Button className="text-button" onClick={() => showToast("Sign in is coming soon.")}>Sign in</Button><Button className="button button-dark compact" onClick={() => showToast("Welcome to Kindred. Your account is ready to set up.")}>Join Kindred <span>↗</span></Button></div><Button className="menu-button" onClick={() => showToast("Mobile navigation is coming soon.")}>☰</Button></header>
    <main>
      <section className="hero" id="discover"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" /> Live from trusted sources</div><h1>Give where it<br /><em>matters now.</em></h1><p className="hero-description">Real-time causes, verified by people on the ground. Find a way to help that feels right for you.</p><div className="hero-actions"><a className="button button-dark" href="#causes">Explore live causes <span>→</span></a><a className="text-link" href="#how-it-works">See how Kindred works <span>↗</span></a></div></div><div className="hero-art" aria-label="A group of people helping one another"><div className="art-sun" /><div className="art-card"><span className="art-card-icon">♥</span><strong>Small gifts.<br />Real momentum.</strong><span className="art-card-foot">Together, we’ve moved $2.4M</span></div><div className="person person-one" /><div className="person person-two" /><div className="person person-three" /><div className="plant plant-one" /><div className="plant plant-two" /></div></section>
      <section className="signal-bar" id="impact"><div><span className="signal-icon">↗</span><strong>$2.4M</strong><span>moved to people in need</span></div><div><span className="signal-icon">◎</span><strong>148</strong><span>active causes right now</span></div><div><span className="signal-icon">✦</span><strong>97%</strong><span>goes directly to the cause</span></div></section>
      <section className="category-section" aria-labelledby="category-heading"><div className="category-heading"><div><div className="eyebrow">Find your way in</div><h2 id="category-heading">Help with<br /><em>intention.</em></h2></div><p>Every kind of care has a place here. Choose what feels close to your heart.</p></div><div className="category-grid">{categories.map((category) => <button className={`category-card ${filter === category.value ? "selected" : ""}`} type="button" key={category.value} onClick={() => selectFilter(category.value)}><span className="category-icon">{category.icon}</span><span className="category-label">{category.label}</span><span className="category-description">{category.description}</span><span className="category-arrow">↗</span></button>)}</div></section>
      <section className="alerts-section" id="alerts" aria-labelledby="alerts-heading"><div className="alerts-copy"><div className="eyebrow"><span className="live-dot" /> Stay close to what matters</div><h2 id="alerts-heading">Know when your<br /><em>community needs you.</em></h2><p>Get a thoughtful alert when a verified need appears near a place you care about. No noise, just meaningful opportunities to help.</p><div className="alert-points"><span>✓ Verified causes only</span><span>✓ You choose what to hear about</span><span>✓ Pause anytime</span></div></div><form className="alert-form" onSubmit={saveAlertPreference}><div className="alert-form-header"><span className="alert-bell">♧</span><div><strong>{alertsEnabled ? "Your local alerts are on" : "Set up local alerts"}</strong><span>{alertsEnabled ? `Watching ${alertLocation}` : "Choose a place to begin"}</span></div></div><label>Location<input value={alertLocation} onChange={(event) => setAlertLocation(event.target.value)} placeholder="City, state, or country" /></label><label>Alert me about<select value={alertCategory} onChange={(event) => setAlertCategory(event.target.value as Category | "all")}><option value="all">All kinds of needs</option>{categories.map((category) => <option key={category.value} value={category.value}>{category.label}</option>)}</select></label><button className="button button-dark alert-submit" type="submit">{alertsEnabled ? "Update alerts" : "Turn on alerts"} <span>↗</span></button>{alertsEnabled && <button className="alert-pause" type="button" onClick={disableAlerts}>Pause alerts</button>}<small>Browser notifications will be added when the live alert service is connected.</small></form></section>
      <section className="causes-section" id="causes"><div className="section-heading"><div><div className="eyebrow">Your kindness, in motion</div><h2>What needs you<br /><em>today.</em></h2></div><div className="heading-side"><p>Browse verified fundraisers and relief efforts updated as the world changes.</p><span className="updated-label"><span className="live-dot" /> Updated just now</span></div></div><div className="toolbar"><label className="search-box"><span aria-hidden="true">⌕</span><input type="search" value={query} onChange={(event) => { setQuery(event.target.value); setVisibleCount(3); }} placeholder="Search causes, places, or needs..." /></label><div className="filter-list" role="group" aria-label="Filter causes">{([["all", "All causes"], ["emergency", "Emergencies"], ["community", "Community"], ["climate", "Climate"]] as const).map(([value, label]) => <Button key={value} className={`filter ${filter === value ? "active" : ""}`} onClick={() => selectFilter(value)}>{label}</Button>)}</div></div><div className="cause-grid">{visible.map((cause) => <article className="cause-card" key={cause.title}><div className="cause-visual"><img src={cause.image} alt="" loading="lazy" /><span className="cause-tag">{cause.tag}</span></div><h3>{cause.title}</h3><p className="cause-location">⌖ {cause.location}</p><div className="progress" aria-label={`${cause.percent}% funded`}><i style={{ width: `${cause.percent}%` }} /></div><div className="cause-meta"><span><strong>{cause.raised}</strong> raised</span><span>of {cause.goal}</span></div><div className="card-footer"><span className="supporters">{cause.supporters}</span><Button className="donate-button" onClick={() => showToast(`Thank you for choosing “${cause.title}”.`)}>Donate now</Button></div></article>)}</div><div className="empty-state" hidden={filtered.length !== 0}>No causes match that search yet. Try another place or need.</div>{visible.length < filtered.length && <Button className="load-more" onClick={() => setVisibleCount((count) => count + 3)}>Load more causes <span>↓</span></Button>}</section>
      <section className="how-section" id="how-it-works"><div className="how-heading"><div className="eyebrow">A little more certainty</div><h2>Good intentions.<br /><em>Clear impact.</em></h2></div><div className="how-grid"><article><span className="step-number">01</span><h3>We find the signal</h3><p>Our team monitors trusted local partners, emergency networks, and community groups.</p></article><article><span className="step-number">02</span><h3>People verify the need</h3><p>Every cause is reviewed for legitimacy, urgency, and a clear path for your gift.</p></article><article><span className="step-number">03</span><h3>You choose your impact</h3><p>Give once or make it a habit. Follow your contribution from here to there.</p></article></div></section>
      <section className="roadmap-section"><div className="roadmap-intro"><div className="eyebrow">Built for the long run</div><h2>More ways to<br /><em>show up.</em></h2><p>Kindred is starting with urgent needs. Here’s where we’re going next.</p></div><div className="roadmap-list"><div className="roadmap-item"><span>⌁</span><div><h3>Personal impact journal</h3><p>See every gift, update, and thank-you in one meaningful timeline.</p></div><b>Coming soon</b></div><div className="roadmap-item"><span>♧</span><div><h3>Monthly giving circles</h3><p>Gather your people and decide together where your money goes.</p></div><b>On the way</b></div><div className="roadmap-item"><span>◌</span><div><h3>Local need alerts</h3><p>Get a gentle nudge when something important happens close to home.</p></div><b>Exploring</b></div></div></section>
    </main><footer className="site-footer"><a className="brand" href="#discover"><span className="brand-mark">✦</span><span>kindred</span></a><p>Built for the moments that matter.</p><span>© 2024 Kindred</span></footer><div className={`toast ${toast ? "show" : ""}`} role="status" aria-live="polite">{toast}</div>
  </>;
}
